[build]
command = "rustup toolchain install nightly-2026-05-01 --component rust-src --component rustc-dev --component llvm-tools-preview --component miri && cargo install mdbook --version 0.4.52 --locked && cargo install mdbook-katex mdbook-repl mdbook-aquascope --locked && cargo +nightly-2026-05-01 install aquascope_front --git https://github.com/cognitive-engineering-lab/aquascope && cd sitp && mdbook build"
publish = "sitp/book"
