[book]
authors = ["j4orz"]
language = "en"
src = "src"
title = "The Structure and Interpretation of Tensor Programs"

[preprocessor.aquascope]

[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = ["theme/css/custom.css"]
additional-js = ["theme/js/highlight-lean.min.js", "theme/js/custom.js"]
default-theme = "light"
preferred-dark-theme = "coal"

[preprocessor.repl]
src = "https://comfy-daifuku-df4422.netlify.app/"
editor.theme = "chrome"
editor.darkTheme = "nord_dark"
python.enable = true
python.loading = "lazy"
